@server = http://localhost:4004


### Results
# @name Results_GET
GET {{server}}/odata/v4/rageval/Results



### Results
# @name Results_POST
POST {{server}}/odata/v4/rageval/Results
Content-Type: application/json

{
  "ID": "8299210a-60be-4ee1-a649-a5c2c18475e0",
  "configuration": {
    "ID": "15458937-2e43-43d4-91bf-8da2c26b1cf8"
  },
  "rating": 81.32,
  "createdAt": "2006-05-25T00:00:00.000Z",
  "createdBy": "createdBy.hsdd@example.net",
  "modifiedAt": "2012-02-27T00:00:00.000Z",
  "modifiedBy": "modifiedBy.hsdd@example.com"
}


### Results
# @name Results_PATCH
PATCH {{server}}/odata/v4/rageval/Results/8299210a-60be-4ee1-a649-a5c2c18475e0
Content-Type: application/json

{
  "ID": "8299210a-60be-4ee1-a649-a5c2c18475e0",
  "configuration": {
    "ID": "15458937-2e43-43d4-91bf-8da2c26b1cf8"
  },
  "rating": 81.32,
  "createdAt": "2006-05-25T00:00:00.000Z",
  "createdBy": "createdBy.hsdd@example.net",
  "modifiedAt": "2012-02-27T00:00:00.000Z",
  "modifiedBy": "modifiedBy.hsdd@example.com"
}


### Results
# @name Results_DELETE
DELETE {{server}}/odata/v4/rageval/Results/8299210a-60be-4ee1-a649-a5c2c18475e0
Content-Type: application/json


### Configuration
# @name Configuration_GET
GET {{server}}/odata/v4/rageval/Configuration



### Configuration
# @name Configuration_POST
POST {{server}}/odata/v4/rageval/Configuration
Content-Type: application/json

{
  "ID": "15458937-2e43-43d4-91bf-8da2c26b1cf8",
  "llmModel": "gpt-4o",
  "taskType": "textExtraction",
  "chunkSize": 1000,
  "chunkOverlap": 100,
  "chunkingMethod": "recursiveChunking",
  "embeddingModel": "ada02"
}


### Configuration
# @name Configuration_PATCH
PATCH {{server}}/odata/v4/rageval/Configuration/15458937-2e43-43d4-91bf-8da2c26b1cf8
Content-Type: application/json

{
  "ID": "15458937-2e43-43d4-91bf-8da2c26b1cf8",
  "llmModel": "llmModel-1545893",
  "taskType": "tableExtraction",
  "chunkSize": 57,
  "chunkOverlap": 0,
  "chunkingMethod": "semanticChunking",
  "embeddingModel": "ada02"
}


### Configuration
# @name Configuration_DELETE
DELETE {{server}}/odata/v4/rageval/Configuration/15458937-2e43-43d4-91bf-8da2c26b1cf8
Content-Type: application/json


### Chunks
# @name Chunks_GET
GET {{server}}/odata/v4/rageval/Chunks



### Chunks
# @name Chunks_POST
POST {{server}}/odata/v4/rageval/Chunks
Content-Type: application/json

{
  "ID": "43748472-90f2-4d19-82d7-977a1faa6576",
  "content": "content-4374847"
}


### Chunks
# @name Chunks_PATCH
PATCH {{server}}/odata/v4/rageval/Chunks/43748472-90f2-4d19-82d7-977a1faa6576
Content-Type: application/json

{
  "ID": "43748472-90f2-4d19-82d7-977a1faa6576",
  "content": "content-4374847"
}


### Chunks
# @name Chunks_DELETE
DELETE {{server}}/odata/v4/rageval/Chunks/43748472-90f2-4d19-82d7-977a1faa6576
Content-Type: application/json


### SourceDocuments
# @name SourceDocuments_GET
GET {{server}}/odata/v4/rageval/SourceDocuments



### SourceDocuments
# @name SourceDocuments_POST
POST {{server}}/odata/v4/rageval/SourceDocuments
Content-Type: application/json

{
  "ID": "715038d1-b7f8-4eaa-9e89-8b4d2ba1caf8",
  "name": "Deutsches Grundgesetz",
  "type": "static",
  "content": ""
}


### SourceDocuments
# @name SourceDocuments_PATCH
PATCH {{server}}/odata/v4/rageval/SourceDocuments/715038d1-b7f8-4eaa-9e89-8b4d2ba1caf8
Content-Type: application/json

{
  "ID": "715038d1-b7f8-4eaa-9e89-8b4d2ba1caf8",
  "type": "static",
  "content": "content-715038"
}


### SourceDocuments
# @name SourceDocuments_DELETE
DELETE {{server}}/odata/v4/rageval/SourceDocuments/715038d1-b7f8-4eaa-9e89-8b4d2ba1caf8
Content-Type: application/json


### test
# @name test_POST
POST {{server}}/odata/v4/rageval/test
Content-Type: application/json

{}


### runTestForConfig
# @name runTestForConfig_POST
POST {{server}}/odata/v4/rageval/runTestForConfig
Content-Type: application/json

{
  "configID": "configID-21970381"
}

### runTestForConfig
# @name createTasks
POST {{server}}/odata/v4/rageval/taskGeneration
Content-Type: application/json

{
  "SourceID": "715038d1-b7f8-4eaa-9e89-8b4d2ba1caf8"
}
